import type { LiveSurfaceEntry } from "@localbrain/shared";

export const LIVE_SURFACE_ENGINE_ID = "ENG-SRF-001";
export const EXPERIENCE_MATURITY_ENGINE_ID = "ENG-EXP-001";

/** Canonical surface registry — live/partial/stub plus experience maturity roadmap. */
export const SURFACE_REGISTRY: LiveSurfaceEntry[] = [
  {
    route: "/",
    label: "Executive Briefing",
    mode: "partial",
    data_sources: ["V1 acceptance", "consolidation opportunity", "CoS orchestration"],
    api_endpoints: ["/api/v1/acceptance", "/api/consolidation/opportunity"],
    stub_sections: [
      { label: "Daily priorities", reason: "Mock briefing sections until LB-OS-089 intelligence composer" },
    ],
    slice_id: "LB-OS-020.5",
    question_id: "EQ-001",
    maturity_level: 2,
    target_maturity_level: 5,
    next_upgrade_slice: "LB-OS-089",
    next_upgrade_summary: "Live intelligence composer replaces mock briefing sections (L4)",
  },
  {
    route: "/workspace/:workspaceId",
    label: "Living Workspace",
    mode: "live",
    data_sources: ["SQLite workspace registry", "ENG-BLD-001 build state", "workspace events", "workspace links"],
    api_endpoints: ["/api/workspaces/:id", "/api/workspaces/:id/events", "/api/workspaces/:id/links"],
    stub_sections: [],
    slice_id: "LB-OS-004",
    question_id: "EQ-007",
    maturity_level: 1,
    target_maturity_level: 5,
    next_upgrade_slice: "LB-OS-033",
    next_upgrade_summary: "Chief recommendations, momentum, deadlines, likely next action (L3)",
  },
  {
    route: "/actions",
    label: "Actions",
    mode: "live",
    data_sources: ["proposed_actions", "action_log", "backup_records"],
    api_endpoints: ["/api/actions/proposed", "/api/actions/log", "/api/actions/backups"],
    stub_sections: [],
    slice_id: "LB-OS-010",
    question_id: "EQ-013",
    maturity_level: 2,
    target_maturity_level: 5,
    next_upgrade_slice: "LB-OS-033",
    next_upgrade_summary: "Batch recommendations, risk scoring, impact estimation (L4)",
  },
  {
    route: "/program-office",
    label: "Executive Program Office",
    mode: "live",
    data_sources: ["PHASE_CHECKLIST", "BUILD_SLICE_QUEUE_V2", "git", "docs index"],
    api_endpoints: ["/api/epo/overview", "/api/epo/docs", "/api/integration/audit"],
    stub_sections: [],
    slice_id: "LB-OS-012.5",
    question_id: "EQ-002",
    maturity_level: 2,
    target_maturity_level: 5,
    next_upgrade_slice: "LB-OS-034",
    next_upgrade_summary: "Velocity trends, schedule slips, risk forecast, architecture hotspots (L4)",
  },
  {
    route: "/system",
    label: "System Health",
    mode: "partial",
    data_sources: ["machine metrics", "storage", "AI usage", "operations counters"],
    api_endpoints: ["/api/system/health"],
    stub_sections: [],
    slice_id: "LB-OS-011",
    question_id: "EQ-003",
    maturity_level: 2,
    target_maturity_level: 4,
    next_upgrade_slice: "LB-OS-010.5",
    next_upgrade_summary: "CoS confidence summaries and workspace priority roll-up (L3)",
  },
  {
    route: "/explorer",
    label: "Knowledge Explorer",
    mode: "live",
    data_sources: ["metadata index", "workspace registry", "permission engine"],
    api_endpoints: ["/api/knowledge-explorer/tree", "/api/knowledge-explorer/executive"],
    stub_sections: [
      { label: "Manual index run", reason: "POST /index/run not exposed in UI yet — LB-OS-007+" },
    ],
    slice_id: "LB-OS-005",
    question_id: "EQ-004",
    maturity_level: 2,
    target_maturity_level: 4,
    next_upgrade_slice: "LB-OS-007",
    next_upgrade_summary: "Six-lens executive insights and on-demand re-index (L3)",
  },
  {
    route: "/studio/engineering",
    label: "Engineering Studio",
    mode: "partial",
    data_sources: ["repo scan", "checklist", "test inventory"],
    api_endpoints: ["/api/engineering/overview"],
    stub_sections: [
      { label: "Specialist routing", reason: "POST /api/engineering/route — UI wiring LB-OS-026+" },
      { label: "Learn / OJT tab", reason: "Academy slice LB-OS-027–032" },
    ],
    slice_id: "LB-OS-012",
    question_id: "EQ-010",
    maturity_level: 2,
    target_maturity_level: 5,
    next_upgrade_slice: "LB-OS-027",
    next_upgrade_summary: "Specialist routing UI and build-along teaching mode (L3)",
  },
  {
    route: "/studio/writing",
    label: "Writing Studio",
    mode: "partial",
    data_sources: ["workspace roots", "template draft assembler"],
    api_endpoints: ["/api/writing/overview", "/api/writing/sources"],
    stub_sections: [
      { label: "Draft preview", reason: "Template assembly — LLM draft path LB-OS-026+" },
      { label: "Learn tab", reason: "Academy slice LB-OS-027–032" },
    ],
    slice_id: "LB-OS-013",
    question_id: "EQ-011",
    maturity_level: 1,
    target_maturity_level: 5,
    next_upgrade_slice: "LB-OS-026",
    next_upgrade_summary: "LLM draft pipeline and Actions save flow (L3)",
  },
  {
    route: "/studio/data",
    label: "Data Intelligence Studio",
    mode: "partial",
    data_sources: ["SQLite registry", "source catalog", "query plan preview"],
    api_endpoints: ["/api/data-intelligence/overview", "/api/data-intelligence/insights"],
    stub_sections: [
      { label: "External sources", reason: "Postgres, Drive, etc. marked planned in catalog" },
      { label: "Learn tab", reason: "Academy slice LB-OS-027–032" },
    ],
    slice_id: "LB-OS-014",
    question_id: "EQ-012",
    maturity_level: 1,
    target_maturity_level: 5,
    next_upgrade_slice: "LB-OS-098",
    next_upgrade_summary: "Live external sources and lineage-backed answers (L3)",
  },
  {
    route: "/studio/relationships",
    label: "Relationship Network",
    mode: "partial",
    data_sources: ["seed catalog", "engagement heuristics"],
    api_endpoints: ["/api/relationship-network/overview", "/api/relationship-network/people/:id"],
    stub_sections: [
      { label: "CRM import", reason: "Illustrative seed catalog — live CRM LB-OS-115+" },
      { label: "Network graph viz", reason: "List view only until graph UI slice" },
      { label: "Learn tab", reason: "Academy slice LB-OS-027–032" },
    ],
    slice_id: "LB-OS-015",
    question_id: "EQ-006",
    maturity_level: 1,
    target_maturity_level: 5,
    next_upgrade_slice: "LB-OS-115",
    next_upgrade_summary: "Live CRM import and actionable engagement (L3)",
  },
  {
    route: "/settings",
    label: "Settings",
    mode: "partial",
    data_sources: ["permission engine", "safety policy"],
    api_endpoints: ["/api/safety/status", "/api/safety/allowed", "/api/safety/forbidden"],
    stub_sections: [
      { label: "Teach Me While We Build", reason: "Local UI toggle — persistence LB-OS-028" },
      { label: "AI providers", reason: "Live at /system/providers (LB-OS-017)" },
    ],
    slice_id: "LB-OS-002",
    maturity_level: 1,
    target_maturity_level: 3,
    next_upgrade_slice: "LB-OS-028",
    next_upgrade_summary: "Persisted preferences and OJT dev-mode integration (L2)",
  },
  {
    route: "/migration",
    label: "Migration Planner",
    mode: "live",
    data_sources: ["migration planner", "drive doctrine", "inventory gate"],
    api_endpoints: ["/api/migration/planner"],
    stub_sections: [],
    slice_id: "LB-OS-018",
    question_id: "EQ-014",
    maturity_level: 2,
    target_maturity_level: 4,
    next_upgrade_slice: "LB-OS-022",
    next_upgrade_summary: "Digital land survey extends Physical World binding model",
  },
  {
    route: "/migration/audit",
    label: "Filesystem Mapping Audit",
    mode: "live",
    data_sources: ["H: drive scan", "mapping heuristics", "unclaimed folder candidates"],
    api_endpoints: ["/api/migration/audit"],
    stub_sections: [],
    slice_id: "LB-OS-019",
    question_id: "EQ-015",
    maturity_level: 2,
    target_maturity_level: 4,
    next_upgrade_slice: "LB-OS-022",
    next_upgrade_summary: "Audit feeds digital land survey (022)",
  },
  {
    route: "/migration/consolidation",
    label: "Executive Consolidation Briefing",
    mode: "live",
    data_sources: ["digital_assets registry", "LB-OS-019 audit", "evidence providers"],
    api_endpoints: [
      "/api/consolidation/briefing",
      "/api/consolidation/:category",
      "/api/consolidation/simulate",
    ],
    stub_sections: [
      { label: "Programs tab", reason: "ProgramEvidenceProvider stub — future slice" },
      { label: "Knowledge tab", reason: "KnowledgeEvidenceProvider stub — future slice" },
      { label: "Proposal generation", reason: "Preview-only simulation in LB-OS-020 — proposals via LB-OS-010 later" },
    ],
    slice_id: "LB-OS-020",
    question_id: "EQ-005",
    maturity_level: 3,
    target_maturity_level: 5,
    next_upgrade_slice: "LB-OS-021",
    next_upgrade_summary: "Consolidation insights feed workspace architecture blueprints",
  },
  {
    route: "/migration/workspace-architecture",
    label: "Executive Workspace Architecture",
    mode: "live",
    data_sources: [
      "workspace registry",
      "LB-OS-019 audit",
      "organization tree",
      "volume health",
    ],
    api_endpoints: ["/api/migration/workspace-architecture"],
    stub_sections: [
      { label: "StorageProvider runtime", reason: "Stub only in 021 — no cloud/NAS execution" },
      { label: "Migration simulation", reason: "Available in LB-OS-023" },
    ],
    slice_id: "LB-OS-021",
    question_id: "EQ-014",
    maturity_level: 3,
    target_maturity_level: 4,
    next_upgrade_slice: "LB-OS-023",
    next_upgrade_summary: "Migration simulation dry-run from survey complexity scores",
  },
  {
    route: "/migration/digital-land-survey",
    label: "Digital Land Survey",
    mode: "live",
    data_sources: [
      "LB-OS-019 audit",
      "LB-OS-021 blueprints",
      "volume health",
      "digital_assets index",
    ],
    api_endpoints: ["/api/migration/digital-land-survey"],
    stub_sections: [
      { label: "Growth trends (historical)", reason: "Index snapshot only — no time-series DB in 022" },
      { label: "NAS/cloud volumes", reason: "Provider stubs only — local C:/H: survey in Phase 1" },
    ],
    slice_id: "LB-OS-022",
    question_id: "EQ-015",
    maturity_level: 3,
    target_maturity_level: 4,
    next_upgrade_slice: "LB-OS-023",
    next_upgrade_summary: "Survey complexity feeds migration simulation batches",
  },
];
