export type InventoryKind='software'|'platform'|'book';export type Evidence='verified'|'grounded'|'estimate';export type Band='sell_now'|'finish_sell'|'incubate'|'publish'|'hold';
export type InventoryItem={id:string;name:string;kind:InventoryKind;readiness:number;disposition:string;repos:string[];customer:string;problem:string;thesis:string;revenue:[number,number];replacement:[number,number];ip:[number,number];commercial:[number,number];remaining:string[];evidence:Evidence;notes:string[]};
const i=(id:string,name:string,kind:InventoryKind,readiness:number,disposition:string,repos:string[],customer:string,problem:string,thesis:string,revenue:[number,number],replacement:[number,number],ip:[number,number],commercial:[number,number],remaining:string[],evidence:Evidence,notes:string[]):InventoryItem=>({id,name,kind,readiness,disposition,repos,customer,problem,thesis,revenue,replacement,ip,commercial,remaining,evidence,notes});
export const inventory:InventoryItem[]=[
i('souschef','SousChef / HomeChef AI','software',90,'ACCELERATE · TRAINING PRODUCT',['Grappe501/HomeChefAi'],'Households seeking meal planning, pantry intelligence and cooking assistance','Food planning is fragmented across recipes, pantry memory, shopping and preferences','A persistent household food brain that learns the kitchen',[150000,600000],[180000,350000],[150000,300000],[600000,1800000],['Billing/entitlement hardening','Paid onboarding','AI cost telemetry','Mobile polish','Privacy controls','Paid beta instrumentation'],'verified',['Existing registry readiness 90%','Persistent pantry/planning and recipe corpus exist']),
i('localbrain','LocalBrain','platform',85,'ACCELERATE · NARROW ICP',['Grappe501/LocalBrain'],'Small organizations and executives needing private operational memory','Teams lose context across files, chats, decisions and departmental workflows','A private/local-first executive operating system with persistent institutional memory',[180000,900000],[250000,550000],[220000,480000],[900000,2700000],['Narrow ideal customer profile','Security hardening','Deployment packaging','Support model','Paid validation'],'grounded',['Existing registry readiness 85%','On-prem/GPU path documented']),
i('campaignos','CampaignOS','software',80,'ACCELERATE · CLEAN EXTRACTION',['Grappe501/CampaignOS','Grappe501/reddirt'],'Political campaigns and civic organizations','Campaign work is split across CRM, field, events, communications, calendar and tasks','One campaign operating system with shared people, project, communications, field and intelligence rails',[240000,1200000],[450000,900000],[350000,750000],[1200000,4200000],['Multi-tenant extraction','Security/permissions hardening','Compliance boundaries','Pricing/packaging','Deployment independence'],'verified',['Real campaign proving ground exists','Existing registry readiness 80%']),
i('votematch','VoteMatch','software',76,'ACCELERATE · HARDEN AUTH/PRIVACY',['Grappe501/VoteMatch'],'Petition campaigns and verification teams','Matching signatures/imported records to voter files is manual and error-prone','Confidence-aware record matching with OCR and mandatory human review',[120000,600000],[180000,400000],[140000,320000],[600000,2000000],['Authentication/RBAC','Privacy controls','Jurisdiction configuration','Audit trail hardening','Commercial packaging'],'verified',['Confidence-aware matching/OCR exists','Human review is a core control']),
i('bidassembly','Bid Assembly','software',65,'ACCELERATE · B2B VALIDATION',['Grappe501/bidapp'],'Contractors, vendors and proposal teams','Complex bids require evidence, requirements, vendors, drafting and compliance to stay synchronized','Grounded proposal assembly tying drafted answers to requirements and evidence',[120000,720000],[160000,360000],[110000,260000],[720000,2400000],['Customer interviews','ICP validation','Pricing','Procurement workflow polish','Enterprise security'],'grounded',['Existing registry readiness 65%']),
i('canonforge','CanonForge Knowledge OS','platform',70,'VALIDATE + EXTRACT',['Grappe501/CanonForge'],'Writers, founders, research teams and complex projects','Projects lose provenance, decisions, canon, contradictions and continuity','Knowledge OS for canon, provenance, contradiction detection and decision history',[120000,600000],[220000,500000],[150000,360000],[600000,2100000],['Standalone extraction','ICP testing','Workflow simplification','Commercial packaging','Multi-user permissions'],'grounded',['Canon/provenance architecture documented']),
i('peoplebase','PeopleBase / ContactList','software',70,'INCUBATE',['Grappe501/PeopleBaseII','Grappe501/ContactList','Grappe501/people'],'Organizations needing a durable people graph','Contact data arrives fragmented, duplicated and disconnected from relationship context','Layered identity/relationship graph preserving source provenance',[120000,600000],[180000,420000],[120000,300000],[600000,1900000],['Canonical schema consolidation','Matching confidence','RBAC','Import UX','Commercial use-case focus'],'grounded',['Multiple related repositories exist']),
i('eventops','Event Operations','software',58,'INCUBATE',['Grappe501/reddirt','Grappe501/kelly-calendar'],'Campaigns, nonprofits, associations and field organizations','Events generate repeatable tasks, staffing, assets, communications and follow-up','Duplicate-ready event project management turning calendar events into operational templates',[90000,450000],[120000,280000],[75000,190000],[450000,1400000],['Independent extraction','Reusable templates','Volunteer assignment','Asset checklists','Post-event reporting'],'grounded',['Built from real campaign event operations']),
i('fieldspark','FieldSpark / Field Command','software',50,'INCUBATE · CAMPAIGNOS MODULE FIRST',['Grappe501/FieldSpark','Grappe501/field-structure','Grappe501/regnat-populus-field','Grappe501/kelly-field-operations'],'Campaign field teams and grassroots organizations','Field programs struggle to translate geographic goals into accountable volunteer work','Field command connecting goals, turf, volunteers, events and voter universes',[120000,600000],[160000,380000],[85000,240000],[600000,1800000],['Unify repositories','CampaignOS module boundary','Mobile field UX','Reporting','Commercial validation'],'estimate',['Several related repositories require consolidation']),
i('bookfoundry','Writers Dashboard / Book Foundry','platform',45,'INCUBATE · PRODUCTIZE',['Grappe501/writers_dashboard','Grappe501/WRITERS_DASHBOARD_M2'],'Authors and research-heavy writers','Long books lose narrative continuity, grounding, chapter state and decisions','Writing companion that remembers the whole book and manages research, canon and revision',[60000,300000],[120000,300000],[60000,180000],[300000,1000000],['UX consolidation','Standalone packaging','Author onboarding','Export workflows','Paid validation'],'grounded',['Multiple writing-system repositories exist']),
i('constitutional-capitalism','Constitutional Capitalism','book',45,'BOOK PRODUCT',['Grappe501/constitutional-capitalism'],'Readers, policy thinkers, civic leaders and educators','Economic reform arguments are fragmented and disconnected from long-run modeling','Public economic framework paired with simulation and evidence',[10000,75000],[80000,180000],[30000,90000],[75000,350000],['Narrative completion','Evidence pass','Simulator integration','Editorial review','Publishing/distribution'],'grounded',['Active manuscript/modeling work exists']),
i('mercy-protocol','The Mercy Protocol','book',85,'BOOK PRODUCT · PUBLICATION TRACK',['Grappe501/Mercy_Protocol'],'General readership','Publication-ready IP needs editorial, production and market packaging','Near-publication manuscript managed as a real commercial asset',[5000,50000],[50000,120000],[30000,80000],[50000,250000],['Final editorial pass','Packaging','Launch plan','Distribution'],'grounded',['Existing registry readiness 85%']),
i('campti','Campti / Grappe Historical Novel','book',30,'BOOK PRODUCT · AUDIT',['Grappe501/campti'],'Historical fiction and regional-history audiences','Family and regional history can disappear without durable narrative IP','Historically grounded multigenerational Louisiana/Arkansas story',[5000,40000],[70000,160000],[20000,60000],[40000,200000],['Manuscript audit','Historical verification','Narrative architecture','Completion plan','Rights review'],'grounded',['Existing registry readiness 30%']),
i('arkansas-history','Arkansas Political History','book',25,'BOOK PRODUCT · AUDIT',['Grappe501/arkansas-political-history'],'Arkansas readers, educators, journalists and civic audiences','State political history is difficult to access as a coherent public narrative','Deeply sourced Arkansas political history connecting institutions, movements and consequences',[5000,30000],[70000,180000],[15000,55000],[30000,180000],['Corpus audit','Source map','Narrative structure','Draft completion','Legal/editorial review'],'estimate',['Existing registry readiness 25%']),
i('arkansas-galaxy','Arkansas Galaxy','book',20,'BOOK PRODUCT · IP REVIEW',['Grappe501/Star_Wars'],'Experimental/fan-fiction audience','Creative work based on protected universes has commercialization constraints','Creative proving ground with reusable techniques subject to IP review',[0,40000],[25000,80000],[0,20000],[0,100000],['IP/legal review','Identify originalizable components','Separate reusable craft'],'estimate',['Commercialization contingent on IP review']),
i('elvestribal','Elvestribal','book',15,'BOOK PRODUCT · CONTENT AUDIT',['Grappe501/Elvestribal','Grappe501/elvestribal-monrepo'],'Fantasy readers','Early creative IP requires consolidation before value can be understood','Original fantasy IP for a long-horizon book/world-building asset',[0,0],[30000,100000],[5000,30000],[0,120000],['Content audit','Repository consolidation','Canon map','Commercial decision'],'estimate',['Existing registry readiness 15%']),
i('county-intelligence','County Intelligence / Workbench','software',60,'INCUBATE',['Grappe501/county-workbench'],'Campaigns, local leaders, developers, journalists and civic organizations','County-level data is scattered and rarely translated into operational intelligence','County operating picture combining demographics, economy, elections, institutions and strategy',[60000,300000],[160000,380000],[90000,240000],[300000,1200000],['Expand county profiles','Automated refresh','Regional rollups','Packaging','Customer validation'],'grounded',['Working county profile architecture exists']),
i('civic-university','Civic University Technology','platform',70,'HOLD · OWNERSHIP/PRIVACY REVIEW',['Grappe501/arkansas-civic-university','Grappe501/ARKANSAS_CIVICS'],'Students, schools, civic organizations and lifelong learners','Civics education is passive and disconnected from durable participation','Mission-driven civic learning converting education into practical participation',[60000,300000],[220000,520000],[90000,260000],[300000,1200000],['Ownership review','Student privacy/legal review','Backend productionization','School rollout controls','Customer validation'],'grounded',['Existing registry readiness 70%','Hold intentional pending ownership/privacy review']),
i('block-street','Block Street','platform',30,'PROVING GROUND',['Grappe501/Block-Street'],'Neighborhood/community participants','Local social/civic participation lacks durable community-owned digital infrastructure','Neighborhood-scale proving ground for coordination, identity, exchange and participation',[30000,180000],[100000,260000],[40000,130000],[180000,700000],['Clarify core loop','Prototype proof','Trust/safety model','Local pilot','Monetization decision'],'estimate',['Existing registry readiness 30%']),
i('news-intelligence','Signal / News Command Center','software',30,'INCUBATE · CONTENT AUDIT',['Grappe501/signal','Grappe501/News-command-center'],'Campaigns, executives, advocates and research teams','Decision-makers drown in news without structured relevance and follow-through','Signal-detection command center turning public information into prioritized decisions/tasks',[60000,300000],[120000,300000],[50000,160000],[300000,1000000],['Repository/content audit','Source architecture','Alerting','User relevance','Commercial validation'],'estimate',['Existing registry readiness 30%']),
i('campaign-compliance','Campaign Compliance','software',35,'INCUBATE · LEGAL ACCURACY GATE',['Grappe501/campaign_compliance','Grappe501/Compliance'],'Political campaigns and committees','Compliance knowledge is fragmented, jurisdiction-specific and high-risk','Human-approved compliance intelligence organizing rules, deadlines, evidence and checks',[60000,300000],[120000,300000],[45000,150000],[300000,1100000],['Legal accuracy gate','Source citations','Jurisdiction versioning','Human approval workflows','Commercial validation'],'estimate',['Legal accuracy is a gating condition'])
];
export const bandFor=(x:InventoryItem):Band=>x.disposition.startsWith('HOLD')?'hold':x.kind==='book'?'publish':x.readiness>=75?'sell_now':x.readiness>=60?'finish_sell':'incubate';
export const priorityFor=(x:InventoryItem)=>Math.round(Math.min(100,x.readiness*.55+(x.evidence==='verified'?15:x.evidence==='grounded'?9:3)+(x.revenue[1]>=600000?12:x.revenue[1]>=300000?8:4)+(bandFor(x)==='sell_now'?12:bandFor(x)==='finish_sell'?8:3)));
export const actionFor=(x:InventoryItem)=>bandFor(x)==='sell_now'?'Get paid proof: package a pilot, set price, name the buyer, and ask for money.':bandFor(x)==='finish_sell'?'Close the smallest launch blockers, then run customer validation.':bandFor(x)==='publish'?'Move through editorial/rights/production gates toward publication.':bandFor(x)==='hold'?'Resolve the governing blocker before adding commercial build spend.':'Validate the customer/problem and consolidate the product before accelerating.';
export const proofFor=(x:InventoryItem)=>bandFor(x)==='sell_now'?'First paid pilot or recurring customer':bandFor(x)==='finish_sell'?'Validated buyer + scoped launch plan':bandFor(x)==='publish'?'Publication-ready manuscript/package + distribution plan':bandFor(x)==='hold'?'Documented clearance of ownership/privacy/legal blocker':'3–5 customer interviews showing repeated willingness to pay';
export const inventorySummary=inventory.reduce((a,x)=>({count:a.count+1,readiness:a.readiness+x.readiness,revenue:[a.revenue[0]+x.revenue[0],a.revenue[1]+x.revenue[1]] as [number,number],replacement:[a.replacement[0]+x.replacement[0],a.replacement[1]+x.replacement[1]] as [number,number],ip:[a.ip[0]+x.ip[0],a.ip[1]+x.ip[1]] as [number,number],commercial:[a.commercial[0]+x.commercial[0],a.commercial[1]+x.commercial[1]] as [number,number]}),{count:0,readiness:0,revenue:[0,0] as [number,number],replacement:[0,0] as [number,number],ip:[0,0] as [number,number],commercial:[0,0] as [number,number]});
