import { academyModules } from "./academyCurriculum.js";
import { getLearnerDashboard } from "./learnerProgress.js";
import { getDatabase } from "../db/database.js";

const glossary:Record<string,string>={repository:"The complete project folder tracked by Git.",commit:"A named checkpoint in project history.",branch:"A separate line of Git work.",deploy:"Publishing a tested build into a runnable environment.",api:"A defined way for software components to communicate.",database:"Durable structured storage used by an application.",frontend:"The interface a user sees and interacts with.",backend:"Server-side logic, APIs, validation and persistence.",prompt:"A build instruction to an AI. In Foundry it should define mission, context, scope, boundaries, acceptance and validation.",diff:"The exact code changes between two states. Review the diff instead of trusting a completion claim.",phase:"A bounded, independently acceptable unit of a Master Build Plan.",pvs:"Phase Value Score: the governed difficulty/value score attached to production work.",capstone:"The product a learner engineers throughout the Academy and must defend to graduate.",fab:"Foundry Advance Balance: recoverable approved Foundry investment in a selected pilot."};

function capstoneState(builderId:string){const db=getDatabase();return (db.prepare(`SELECT id,status,title,updated_at FROM foundry_capstone_notebooks WHERE builder_id=? ORDER BY created_at DESC LIMIT 1`).get(builderId) as any)??null;}
function productionState(builderId:string){const db=getDatabase();return db.prepare(`SELECT id,phase_id,status,updated_at FROM foundry_production_assignments WHERE builder_id=? ORDER BY created_at DESC LIMIT 5`).all(builderId) as any[];}

export function getAutonomousCoach(enrollmentId:string){const d=getLearnerDashboard(enrollmentId);if(!d)return null;const current=d.currentModule;const gate=d.gates.find((g:any)=>g.stage_id===d.enrollment.current_stage_id);const capstone=capstoneState(d.enrollment.builder_id);const production=productionState(d.enrollment.builder_id);let next={kind:"lesson",label:`Continue ${current?.id??"Academy"}: ${current?.title??"current lesson"}`,reason:"Your current curriculum module is the next bounded action."};if(d.enrollment.status==="remediation")next={kind:"remediation",label:`Repair ${current?.id??"current module"}`,reason:"The last attempt needs correction before progression."};else if(gate?.status==="ready")next={kind:"gate",label:`Complete ${d.currentStage?.title??"stage"} gate`,reason:"All lessons in this stage are complete; progression is waiting on its gate."};else if(d.enrollment.status==="graduation_ready")next={kind:"capstone",label:"Finish Capstone graduation path",reason:"Curriculum gates are complete; graduation still requires the Capstone process."};return {learner:{builderId:d.enrollment.builder_id,status:d.enrollment.status,percentComplete:d.metrics.percentComplete},today:{stage:d.currentStage,module:current,nextAction:next},capstone,production,coach:{mode:"self_guided",principles:["Explain before assuming prior knowledge.","Give one unmistakable next action.","Teach the reason behind the step, not just clicks.","Use inspect-first and bounded-change discipline.","Never claim code works without validation evidence.","Escalate production acceptance and major gates to independent review."],suggestedQuestions:["Explain this lesson in plain English","What does this term mean?","Why is this step necessary?","Show me how this connects to my Capstone","What evidence will prove I finished?"]}};}
export function defineTerm(term:string){const key=term.trim().toLowerCase();return glossary[key]?{term:key,definition:glossary[key]}:null;}
export function getLessonExperience(moduleId:string){const m=academyModules.find(x=>x.id===moduleId);if(!m)return null;return {module:m,lessonPattern:["Why this matters","Plain-English concept","Watch/Read","Guided example","Do it yourself","Prove it","Reflect","Connect it to your Capstone"],coachPrompts:[`Explain ${m.title} like I have never coded before.`,`Give me a guided exercise for ${m.title}.`,`What mistakes should I watch for in ${m.title}?`,`How does ${m.title} affect a real Master Build Plan?`]};}
