import {randomUUID} from 'node:crypto';import {getDatabase} from '../db/database.js';import {academyStages} from './academyCurriculum.js';
export function migrateCohortLaunchTables():void{getDatabase().exec(`
CREATE TABLE IF NOT EXISTS foundry_cohort_launch_plans(id TEXT PRIMARY KEY,cohort_id TEXT NOT NULL UNIQUE,start_date TEXT NOT NULL,end_date TEXT NOT NULL,weekly_hours REAL NOT NULL DEFAULT 15,reviewer_capacity_per_week INTEGER NOT NULL DEFAULT 10,status TEXT NOT NULL DEFAULT 'draft',created_by TEXT NOT NULL,launch_decision TEXT,decision_by TEXT,decision_rationale TEXT,created_at TEXT NOT NULL DEFAULT (datetime('now')),updated_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS foundry_cohort_invitations(id TEXT PRIMARY KEY,cohort_id TEXT NOT NULL,email TEXT,name TEXT,invite_code TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'invited',created_at TEXT NOT NULL DEFAULT (datetime('now')),accepted_at TEXT);
CREATE TABLE IF NOT EXISTS foundry_cohort_week_plan(id TEXT PRIMARY KEY,cohort_id TEXT NOT NULL,week_no INTEGER NOT NULL,stage_id TEXT NOT NULL,target_label TEXT NOT NULL,target_modules_json TEXT NOT NULL DEFAULT '[]',review_slots_required INTEGER NOT NULL DEFAULT 0,UNIQUE(cohort_id,week_no));
CREATE TABLE IF NOT EXISTS foundry_cohort_activity(id TEXT PRIMARY KEY,cohort_id TEXT NOT NULL,enrollment_id TEXT,event_type TEXT NOT NULL,details_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS foundry_cohort_nudges(id TEXT PRIMARY KEY,cohort_id TEXT NOT NULL,enrollment_id TEXT NOT NULL,nudge_type TEXT NOT NULL,message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',created_at TEXT NOT NULL DEFAULT (datetime('now')),sent_at TEXT);
CREATE TABLE IF NOT EXISTS foundry_cohort_launch_checks(id TEXT PRIMARY KEY,cohort_id TEXT NOT NULL,check_key TEXT NOT NULL,label TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',signed_by TEXT,notes TEXT,updated_at TEXT NOT NULL DEFAULT (datetime('now')),UNIQUE(cohort_id,check_key));
`);}
function addDays(iso:string,d:number){const x=new Date(`${iso}T12:00:00Z`);x.setUTCDate(x.getUTCDate()+d);return x.toISOString().slice(0,10)}
export function createCohortLaunchPlan(input:{name:string;startDate:string;capacity:number;trainingProductId?:string;weeklyHours?:number;reviewerCapacityPerWeek?:number;createdBy:string}){const db=getDatabase();const cohortId=randomUUID();const endDate=addDays(input.startDate,83);db.transaction(()=>{db.prepare(`INSERT INTO foundry_cohorts(id,name,status,starts_on,ends_on,capacity,training_product_id) VALUES(?,?,'planning',?,?,?,?)`).run(cohortId,input.name,input.startDate,endDate,input.capacity,input.trainingProductId??null);db.prepare(`INSERT INTO foundry_cohort_launch_plans(id,cohort_id,start_date,end_date,weekly_hours,reviewer_capacity_per_week,created_by) VALUES(?,?,?,?,?,?,?)`).run(randomUUID(),cohortId,input.startDate,endDate,input.weeklyHours??15,input.reviewerCapacityPerWeek??10,input.createdBy);academyStages.forEach((s,i)=>{const week=Math.min(12,Math.max(1,i+1));db.prepare(`INSERT INTO foundry_cohort_week_plan(id,cohort_id,week_no,stage_id,target_label,target_modules_json,review_slots_required) VALUES(?,?,?,?,?,?,?)`).run(randomUUID(),cohortId,week,s.id,s.title,JSON.stringify(s.moduleIds),s.order>=5?3:1)});for(const [key,label] of [['curriculum','Curriculum content ready'],['reviewers','Reviewer capacity assigned'],['training_product','Training product ready'],['legal','Employment/IP agreements reviewed'],['payroll','Payroll process ready'],['ai','AI provider configured'],['dry_run','Cohort dry run passed']])db.prepare(`INSERT INTO foundry_cohort_launch_checks(id,cohort_id,check_key,label) VALUES(?,?,?,?)`).run(randomUUID(),cohortId,key,label);})();return getCohortLaunchDashboard(cohortId);}
export function inviteToCohort(input:{cohortId:string;email?:string;name?:string}){const id=randomUUID(),code=randomUUID().slice(0,8);getDatabase().prepare(`INSERT INTO foundry_cohort_invitations(id,cohort_id,email,name,invite_code) VALUES(?,?,?,?,?)`).run(id,input.cohortId,input.email??null,input.name??null,code);return {id,inviteCode:code,status:'invited'};}
export function signLaunchCheck(input:{cohortId:string;checkKey:string;actorId:string;pass:boolean;notes?:string}){getDatabase().prepare(`UPDATE foundry_cohort_launch_checks SET status=?,signed_by=?,notes=?,updated_at=datetime('now') WHERE cohort_id=? AND check_key=?`).run(input.pass?'passed':'blocked',input.actorId,input.notes??null,input.cohortId,input.checkKey);return getCohortLaunchDashboard(input.cohortId);}
export function queueNudges(cohortId:string){const db=getDatabase();const rows=db.prepare(`SELECT id,builder_id,status,updated_at FROM foundry_academy_enrollments WHERE cohort_id=? AND status IN('active','remediation')`).all(cohortId) as any[];let count=0;for(const e of rows){const days=Math.floor((Date.now()-new Date(e.updated_at+'Z').getTime())/86400000);if(days>=3||e.status==='remediation'){db.prepare(`INSERT INTO foundry_cohort_nudges(id,cohort_id,enrollment_id,nudge_type,message) VALUES(?,?,?,?,?)`).run(randomUUID(),cohortId,e.id,e.status==='remediation'?'remediation':'inactive',e.status==='remediation'?'Your current module needs remediation. Open the Academy and follow the repair packet.':'You have been inactive for several days. Open the Academy to see your next action.');count++;}}return {queued:count};}
export function decideCohortLaunch(input:{cohortId:string;actorId:string;decision:'launch'|'hold';rationale:string}){const d=getCohortLaunchDashboard(input.cohortId);if(!d)return {ok:false,error:'cohort_not_found'};if(input.decision==='launch'&&!d.readiness.ready)return {ok:false,error:'launch_checks_incomplete',readiness:d.readiness};getDatabase().transaction(()=>{getDatabase().prepare(`UPDATE foundry_cohort_launch_plans SET launch_decision=?,decision_by=?,decision_rationale=?,status=?,updated_at=datetime('now') WHERE cohort_id=?`).run(input.decision,input.actorId,input.rationale,input.decision==='launch'?'launched':'hold',input.cohortId);getDatabase().prepare(`UPDATE foundry_cohorts SET status=? WHERE id=?`).run(input.decision==='launch'?'active':'hold',input.cohortId);})();return {ok:true,dashboard:getCohortLaunchDashboard(input.cohortId)};}
export function getCohortLaunchDashboard(cohortId:string){const db=getDatabase();const cohort=db.prepare(`SELECT * FROM foundry_cohorts WHERE id=?`).get(cohortId) as any;if(!cohort)return null;const plan=db.prepare(`SELECT * FROM foundry_cohort_launch_plans WHERE cohort_id=?`).get(cohortId) as any;const checks=db.prepare(`SELECT * FROM foundry_cohort_launch_checks WHERE cohort_id=? ORDER BY rowid`).all(cohortId) as any[];const invitations=db.prepare(`SELECT * FROM foundry_cohort_invitations WHERE cohort_id=? ORDER BY created_at`).all(cohortId);const weeks=db.prepare(`SELECT * FROM foundry_cohort_week_plan WHERE cohort_id=? ORDER BY week_no`).all(cohortId) as any[];const learners=db.prepare(`SELECT * FROM foundry_academy_enrollments WHERE cohort_id=? ORDER BY started_at`).all(cohortId) as any[];const nudges=db.prepare(`SELECT * FROM foundry_cohort_nudges WHERE cohort_id=? ORDER BY created_at DESC`).all(cohortId);const requiredReviews=weeks.reduce((s,w)=>s+Number(w.review_slots_required||0),0);const capacity=Number(plan?.reviewer_capacity_per_week??0)*12;const checksPassed=checks.filter(c=>c.status==='passed').length;const readinessPct=Math.round((checksPassed/checks.length)*80+Math.min(20,capacity?Math.min(1,requiredReviews/capacity===0?1:capacity/requiredReviews)*20:0));return {cohort,plan,weeks,invitations,learners,nudges,reviewCapacity:{requiredSlots:requiredReviews,availableSlots:capacity,adequate:capacity>=requiredReviews},readiness:{checksPassed,checksTotal:checks.length,percent:readinessPct,ready:checks.every(c=>c.status==='passed')&&capacity>=requiredReviews},checks,doctrine:{launchRequiresExplicitOperatorDecision:true,automaticDismissal:false,automaticApproval:false,financialExecutionEnabled:false}};}
export function listCohortLaunchPlans(){return getDatabase().prepare(`SELECT c.*,p.launch_decision,p.reviewer_capacity_per_week FROM foundry_cohorts c LEFT JOIN foundry_cohort_launch_plans p ON p.cohort_id=c.id ORDER BY c.created_at DESC`).all();}
