import { randomUUID } from "node:crypto";
import { getDatabase } from "../db/database.js";
import { getCapstoneApplication } from "./capstoneDefense.js";

export function migratePilotFundingTables():void { getDatabase().exec(`
CREATE TABLE IF NOT EXISTS foundry_pilot_funding_authorizations (id TEXT PRIMARY KEY,application_id TEXT NOT NULL UNIQUE,builder_id TEXT NOT NULL,approved_budget_usd REAL NOT NULL,status TEXT NOT NULL DEFAULT 'authorized',authorized_by TEXT NOT NULL,rationale TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS foundry_advance_ledger (id TEXT PRIMARY KEY,authorization_id TEXT NOT NULL,event_type TEXT NOT NULL,amount_usd REAL NOT NULL,balance_after_usd REAL NOT NULL,reference TEXT,recorded_by TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS foundry_revenue_recovery_ledger (id TEXT PRIMARY KEY,authorization_id TEXT NOT NULL,period_key TEXT NOT NULL,eligible_revenue_usd REAL NOT NULL,recovery_rate REAL NOT NULL,recovery_amount_usd REAL NOT NULL,operating_amount_usd REAL NOT NULL,balance_after_usd REAL NOT NULL,recorded_by TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')),UNIQUE(authorization_id,period_key));
CREATE TABLE IF NOT EXISTS foundry_residual_formulas (id TEXT PRIMARY KEY,authorization_id TEXT NOT NULL UNIQUE,company_pct REAL NOT NULL,lead_pct REAL NOT NULL,team_pct REAL NOT NULL,status TEXT NOT NULL DEFAULT 'prepared',approved_by TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
`); }

function decisionFor(applicationId:string){return getDatabase().prepare(`SELECT * FROM foundry_capstone_decisions WHERE application_id=?`).get(applicationId) as any;}
function authorization(id:string){return getDatabase().prepare(`SELECT * FROM foundry_pilot_funding_authorizations WHERE id=?`).get(id) as any;}
function balance(id:string){const r=getDatabase().prepare(`SELECT balance_after_usd FROM foundry_advance_ledger WHERE authorization_id=? ORDER BY created_at DESC,rowid DESC LIMIT 1`).get(id) as any;return Number(r?.balance_after_usd??0);}

export function authorizePilotFunding(input:{applicationId:string;authorizedBy:string;approvedBudgetUsd:number;rationale:string}){
 const app=getCapstoneApplication(input.applicationId); if(!app)return {ok:false,error:"application_not_found"}; const d=decisionFor(app.id); if(!d||d.graduation_decision!=="graduate"||d.pilot_decision!=="selected")return {ok:false,error:"selected_graduated_pilot_required"}; if(app.builder_id===input.authorizedBy)return {ok:false,error:"self_funding_authorization_forbidden"}; const budget=Number(input.approvedBudgetUsd); if(!(budget>0))return {ok:false,error:"positive_budget_required"}; const id=randomUUID();
 try{getDatabase().transaction(()=>{getDatabase().prepare(`INSERT INTO foundry_pilot_funding_authorizations (id,application_id,builder_id,approved_budget_usd,authorized_by,rationale) VALUES (?,?,?,?,?,?)`).run(id,app.id,app.builder_id,budget,input.authorizedBy,input.rationale);getDatabase().prepare(`INSERT INTO foundry_advance_ledger (id,authorization_id,event_type,amount_usd,balance_after_usd,reference,recorded_by) VALUES (?,?,?,?,?,?,?)`).run(randomUUID(),id,"authorization",budget,budget,"approved pilot budget",input.authorizedBy);})();}catch{return {ok:false,error:"pilot_already_authorized"};} return {ok:true,authorization:authorization(id),foundryAdvanceBalance:budget,financialExecutionEnabled:false};
}

export function recordApprovedProjectCost(input:{authorizationId:string;amountUsd:number;reference:string;recordedBy:string}){const a=authorization(input.authorizationId);if(!a)return {ok:false,error:"authorization_not_found"};const amt=Number(input.amountUsd);if(!(amt>0))return {ok:false,error:"positive_cost_required"};const current=balance(a.id);const next=current+amt;getDatabase().prepare(`INSERT INTO foundry_advance_ledger (id,authorization_id,event_type,amount_usd,balance_after_usd,reference,recorded_by) VALUES (?,?,?,?,?,?,?)`).run(randomUUID(),a.id,"approved_cost",amt,next,input.reference,input.recordedBy);return {ok:true,foundryAdvanceBalance:next,financialExecutionEnabled:false};}

export function recordRevenuePeriod(input:{authorizationId:string;periodKey:string;eligibleRevenueUsd:number;recordedBy:string}){const a=authorization(input.authorizationId);if(!a)return {ok:false,error:"authorization_not_found"};const revenue=Math.max(0,Number(input.eligibleRevenueUsd));const current=balance(a.id);const recovery=Math.min(current,revenue*0.5);const operating=revenue-recovery;const next=Math.max(0,current-recovery);try{getDatabase().transaction(()=>{getDatabase().prepare(`INSERT INTO foundry_revenue_recovery_ledger (id,authorization_id,period_key,eligible_revenue_usd,recovery_rate,recovery_amount_usd,operating_amount_usd,balance_after_usd,recorded_by) VALUES (?,?,?,?,?,?,?,?,?)`).run(randomUUID(),a.id,input.periodKey,revenue,0.5,recovery,operating,next,input.recordedBy);getDatabase().prepare(`INSERT INTO foundry_advance_ledger (id,authorization_id,event_type,amount_usd,balance_after_usd,reference,recorded_by) VALUES (?,?,?,?,?,?,?)`).run(randomUUID(),a.id,"recovery",-recovery,next,input.periodKey,input.recordedBy);if(next===0)getDatabase().prepare(`UPDATE foundry_pilot_funding_authorizations SET status='recovered' WHERE id=?`).run(a.id);})();}catch{return {ok:false,error:"period_already_recorded"};}return {ok:true,recoveryAmountUsd:recovery,operatingAmountUsd:operating,foundryAdvanceBalance:next,recoveryComplete:next===0,financialExecutionEnabled:false};}

export function prepareResidualFormula(input:{authorizationId:string;companyPct:number;leadPct:number;teamPct:number;approvedBy:string}){const a=authorization(input.authorizationId);if(!a)return {ok:false,error:"authorization_not_found"};const c=Number(input.companyPct),l=Number(input.leadPct),t=Number(input.teamPct);if(Math.abs(c+l+t-100)>0.001)return {ok:false,error:"residual_must_total_100"};if(c<25)return {ok:false,error:"company_floor_25"};if(l>51)return {ok:false,error:"lead_ceiling_51"};if(Math.min(c,l,t)<0)return {ok:false,error:"negative_residual_forbidden"};getDatabase().prepare(`INSERT INTO foundry_residual_formulas (id,authorization_id,company_pct,lead_pct,team_pct,approved_by) VALUES (?,?,?,?,?,?) ON CONFLICT(authorization_id) DO UPDATE SET company_pct=excluded.company_pct,lead_pct=excluded.lead_pct,team_pct=excluded.team_pct,approved_by=excluded.approved_by,status='prepared'`).run(randomUUID(),a.id,c,l,t,input.approvedBy);return {ok:true,active:balance(a.id)===0,financialExecutionEnabled:false};}

export function getPilotFundingDashboard(id:string){const a=authorization(id);if(!a)return null;const db=getDatabase(),fab=balance(id),formula=db.prepare(`SELECT * FROM foundry_residual_formulas WHERE authorization_id=?`).get(id)??null;return {authorization:a,foundryAdvanceBalance:fab,advanceLedger:db.prepare(`SELECT * FROM foundry_advance_ledger WHERE authorization_id=? ORDER BY created_at,rowid`).all(id),revenueRecovery:db.prepare(`SELECT * FROM foundry_revenue_recovery_ledger WHERE authorization_id=? ORDER BY created_at,rowid`).all(id),residualFormula:formula,recoveryRate:0.5,recoveryComplete:fab===0,residualFormulaEligible:fab===0&&!!formula,doctrine:{eligibleRevenueDefinitionRequiresAccountingApproval:true,companyResidualFloorPct:25,leadResidualCeilingPct:51,financialExecutionEnabled:false,payrollEnabled:false,equityIssuanceEnabled:false,residualSettlementEnabled:false,moneyMovementEnabled:false}};}
