import {randomUUID} from 'node:crypto';import {getDatabase} from '../db/database.js';
export type RepairPriority='P0'|'P1'|'P2'|'P3';
export function migrateStabilizationTables():void{getDatabase().exec(`
CREATE TABLE IF NOT EXISTS foundry_academy_repair_items(id TEXT PRIMARY KEY,defect_id TEXT NOT NULL UNIQUE,dry_run_id TEXT NOT NULL,priority TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'backlog',owner TEXT,target_slice TEXT,repair_plan TEXT NOT NULL DEFAULT '',acceptance_criteria_json TEXT NOT NULL DEFAULT '[]',evidence_json TEXT NOT NULL DEFAULT '[]',created_at TEXT NOT NULL DEFAULT (datetime('now')),updated_at TEXT NOT NULL DEFAULT (datetime('now')),closed_at TEXT);
CREATE TABLE IF NOT EXISTS foundry_academy_repair_events(id TEXT PRIMARY KEY,repair_item_id TEXT NOT NULL,event_type TEXT NOT NULL,actor_id TEXT NOT NULL,details_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS foundry_academy_stabilization_runs(id TEXT PRIMARY KEY,label TEXT NOT NULL,source_dry_run_id TEXT,open_p0 INTEGER NOT NULL DEFAULT 0,open_p1 INTEGER NOT NULL DEFAULT 0,open_total INTEGER NOT NULL DEFAULT 0,readiness TEXT NOT NULL,summary_json TEXT NOT NULL DEFAULT '{}',created_by TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')));
`);}
function priorityFor(severity:string,area:string):RepairPriority{if(severity==='blocker')return'P0';if(['governance','finance','persistence','certification'].includes(area))return'P1';if(['curriculum','operations','cohort','capstone','economics'].includes(area))return'P2';return'P3';}
function criteriaFor(defect:any){const base=[`Reproduce or verify the defect: ${defect.title}.`,`Implement a bounded repair without weakening governance or financial locks.`,`Attach validation evidence proving the defect no longer reproduces.`];if(defect.severity==='blocker')base.push('Re-run the affected dry-run check and obtain PASS before closure.');return base;}
export function importDryRunDefects(dryRunId:string,actorId:string){const db=getDatabase();const defects=db.prepare(`SELECT * FROM foundry_academy_defects WHERE dry_run_id=? AND status!='resolved' ORDER BY severity DESC,created_at`).all(dryRunId) as any[];let created=0;for(const d of defects){const existing=db.prepare(`SELECT id FROM foundry_academy_repair_items WHERE defect_id=?`).get(d.id);if(existing)continue;const id=randomUUID();const priority=priorityFor(d.severity,d.area);db.prepare(`INSERT INTO foundry_academy_repair_items(id,defect_id,dry_run_id,priority,status,owner,target_slice,repair_plan,acceptance_criteria_json) VALUES(?,?,?,?,?,?,?,?,?)`).run(id,d.id,dryRunId,priority,'backlog',d.owner??null,'CF-013',`Repair ${d.area}: ${d.title}`,JSON.stringify(criteriaFor(d)));db.prepare(`INSERT INTO foundry_academy_repair_events(id,repair_item_id,event_type,actor_id,details_json) VALUES(?,?,?,?,?)`).run(randomUUID(),id,'imported',actorId,JSON.stringify({defectId:d.id,severity:d.severity,area:d.area}));created++;}return{created,queue:getRepairQueue()};}
export function updateRepairItem(input:{id:string;actorId:string;status?:string;owner?:string;repairPlan?:string;evidence?:unknown[]}){const db=getDatabase();const row=db.prepare(`SELECT * FROM foundry_academy_repair_items WHERE id=?`).get(input.id) as any;if(!row)return{ok:false,error:'repair_item_not_found'};const status=input.status??row.status;if(status==='closed'){const evidence=input.evidence??JSON.parse(row.evidence_json||'[]');if(!Array.isArray(evidence)||evidence.length===0)return{ok:false,error:'closure_evidence_required'};const defect=db.prepare(`SELECT * FROM foundry_academy_defects WHERE id=?`).get(row.defect_id) as any;if(defect?.severity==='blocker'&&!evidence.some((x:any)=>String(typeof x==='string'?x:x?.type??x?.label??'').toLowerCase().includes('pass')))return{ok:false,error:'blocking_repair_requires_pass_evidence'};}
db.transaction(()=>{db.prepare(`UPDATE foundry_academy_repair_items SET status=?,owner=?,repair_plan=?,evidence_json=?,updated_at=datetime('now'),closed_at=CASE WHEN ?='closed' THEN datetime('now') ELSE closed_at END WHERE id=?`).run(status,input.owner??row.owner,input.repairPlan??row.repair_plan,JSON.stringify(input.evidence??JSON.parse(row.evidence_json||'[]')),status,input.id);db.prepare(`INSERT INTO foundry_academy_repair_events(id,repair_item_id,event_type,actor_id,details_json) VALUES(?,?,?,?,?)`).run(randomUUID(),input.id,status,input.actorId,JSON.stringify({owner:input.owner??row.owner,repairPlan:input.repairPlan??row.repair_plan,evidence:input.evidence??[]}));if(status==='closed')db.prepare(`UPDATE foundry_academy_defects SET status='resolved',owner=?,resolved_at=datetime('now'),detail=detail||? WHERE id=?`).run(input.owner??input.actorId,'\nResolved through CF-013 repair evidence.',row.defect_id);})();return{ok:true,item:getRepairItem(input.id)};}
export function getRepairItem(id:string){const db=getDatabase();const item=db.prepare(`SELECT r.*,d.area,d.severity,d.title,d.detail FROM foundry_academy_repair_items r JOIN foundry_academy_defects d ON d.id=r.defect_id WHERE r.id=?`).get(id) as any;if(!item)return null;return{...item,acceptanceCriteria:JSON.parse(item.acceptance_criteria_json||'[]'),evidence:JSON.parse(item.evidence_json||'[]'),events:db.prepare(`SELECT * FROM foundry_academy_repair_events WHERE repair_item_id=? ORDER BY created_at`).all(id)};}
export function getRepairQueue(){const db=getDatabase();const items=db.prepare(`SELECT r.*,d.area,d.severity,d.title FROM foundry_academy_repair_items r JOIN foundry_academy_defects d ON d.id=r.defect_id ORDER BY CASE r.priority WHEN 'P0' THEN 0 WHEN 'P1' THEN 1 WHEN 'P2' THEN 2 ELSE 3 END,r.created_at`).all() as any[];const open=items.filter(x=>x.status!=='closed');return{summary:{total:items.length,open:open.length,p0:open.filter(x=>x.priority==='P0').length,p1:open.filter(x=>x.priority==='P1').length,p2:open.filter(x=>x.priority==='P2').length,p3:open.filter(x=>x.priority==='P3').length,closed:items.length-open.length},items};}
export function runStabilizationAssessment(input:{label?:string;sourceDryRunId?:string;createdBy:string}){const q=getRepairQueue();const readiness=q.summary.p0>0?'NO_LAUNCH':q.summary.p1>0?'HOLD_FOR_REPAIR':q.summary.open>0?'CONDITIONAL':'READY_FOR_CERTIFICATION';const id=randomUUID();const summary={repairQueue:q.summary,doctrine:{featureFreeze:true,criticalDefectsBlockLaunch:true,closureRequiresEvidence:true,financialExecutionEnabled:false}};getDatabase().prepare(`INSERT INTO foundry_academy_stabilization_runs(id,label,source_dry_run_id,open_p0,open_p1,open_total,readiness,summary_json,created_by) VALUES(?,?,?,?,?,?,?,?,?)`).run(id,input.label??'CF-013 Stabilization Assessment',input.sourceDryRunId??null,q.summary.p0,q.summary.p1,q.summary.open,readiness,JSON.stringify(summary),input.createdBy);return{id,readiness,...summary};}
export function getStabilizationDashboard(){const q=getRepairQueue();const latest=getDatabase().prepare(`SELECT * FROM foundry_academy_stabilization_runs ORDER BY created_at DESC LIMIT 1`).get()??null;return{queue:q,latest,launchRule:q.summary.p0>0?'NO_LAUNCH':q.summary.p1>0?'HOLD_FOR_REPAIR':q.summary.open>0?'CONDITIONAL':'READY_FOR_CERTIFICATION',doctrine:{featureFreeze:true,newFeaturesRequireDefectJustification:true,repairEvidenceRequired:true,financialExecutionEnabled:false}};}
