import {randomUUID} from 'node:crypto';import {getDatabase} from '../db/database.js';
export type WorkstationCheckResult={id:string;label:string;command?:string;status:'pass'|'fail'|'warn';detail:string;durationMs?:number};
export function migrateWorkstationCertificationTables():void{getDatabase().exec(`
CREATE TABLE IF NOT EXISTS foundry_workstation_certification_runs(id TEXT PRIMARY KEY,label TEXT NOT NULL,status TEXT NOT NULL,score REAL NOT NULL DEFAULT 0,blocking_failures INTEGER NOT NULL DEFAULT 0,warning_count INTEGER NOT NULL DEFAULT 0,evidence_json TEXT NOT NULL DEFAULT '[]',created_by TEXT NOT NULL,source_dry_run_id TEXT,created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS foundry_workstation_evidence(id TEXT PRIMARY KEY,run_id TEXT NOT NULL,check_id TEXT NOT NULL,label TEXT NOT NULL,command TEXT,status TEXT NOT NULL,detail TEXT NOT NULL,duration_ms INTEGER,created_at TEXT NOT NULL DEFAULT (datetime('now')),UNIQUE(run_id,check_id));
`);try{getDatabase().exec(`ALTER TABLE foundry_workstation_certification_runs ADD COLUMN source_dry_run_id TEXT`)}catch{}
}
export function importWorkstationEvidence(input:{label?:string;createdBy:string;checks:WorkstationCheckResult[]}){const checks=input.checks??[];const blockers=checks.filter(c=>c.status==='fail').length;const warnings=checks.filter(c=>c.status==='warn').length;const score=checks.length?Math.round(checks.reduce((s,c)=>s+(c.status==='pass'?1:c.status==='warn'?.5:0),0)/checks.length*100):0;const id=randomUUID();const dryRunId=randomUUID();const status=blockers?'no_launch':warnings?'conditional':'pass';const db=getDatabase();db.transaction(()=>{db.prepare(`INSERT INTO foundry_academy_dry_runs(id,label,status,score,blocking_defects,warning_count,checks_json,created_by) VALUES(?,?,?,?,?,?,?,?)`).run(dryRunId,`${input.label??'Workstation Certification'} — machine evidence`,blockers?'no_launch':warnings?'conditional':'candidate',score,blockers,warnings,JSON.stringify(checks.map(c=>({id:`workstation:${c.id}`,area:'certification',label:c.label,status:c.status,detail:c.detail,blocking:c.status==='fail'}))),input.createdBy);db.prepare(`INSERT INTO foundry_workstation_certification_runs(id,label,status,score,blocking_failures,warning_count,evidence_json,created_by,source_dry_run_id) VALUES(?,?,?,?,?,?,?,?,?)`).run(id,input.label??'Workstation Certification',status,score,blockers,warnings,JSON.stringify(checks),input.createdBy,dryRunId);for(const c of checks){db.prepare(`INSERT INTO foundry_workstation_evidence(id,run_id,check_id,label,command,status,detail,duration_ms) VALUES(?,?,?,?,?,?,?,?)`).run(randomUUID(),id,c.id,c.label,c.command??null,c.status,c.detail,c.durationMs??null);if(c.status!=='pass')db.prepare(`INSERT INTO foundry_academy_defects(id,dry_run_id,area,severity,title,detail) VALUES(?,?,?,?,?,?)`).run(randomUUID(),dryRunId,'certification',c.status==='fail'?'blocker':'warning',`Workstation: ${c.label}`,`${c.command??''}\n${c.detail}`);}})();return getWorkstationCertificationRun(id);}
export function getWorkstationCertificationRun(id:string){const db=getDatabase();const run=db.prepare(`SELECT * FROM foundry_workstation_certification_runs WHERE id=?`).get(id) as any;if(!run)return null;return{run:{...run,evidence:JSON.parse(run.evidence_json||'[]')},evidence:db.prepare(`SELECT * FROM foundry_workstation_evidence WHERE run_id=? ORDER BY rowid`).all(id),repairBridge:{dryRunId:run.source_dry_run_id,importEndpoint:run.source_dry_run_id?`/api/foundry/academy/stabilization/import/${run.source_dry_run_id}`:null}};}
export function listWorkstationCertificationRuns(){return getDatabase().prepare(`SELECT id,label,status,score,blocking_failures,warning_count,created_by,source_dry_run_id,created_at FROM foundry_workstation_certification_runs ORDER BY created_at DESC`).all();}
