import type { WritingDraftPreview, WritingModeId, WritingVoiceId } from "@localbrain/shared";
import { getWritingMode } from "./writingModes.js";
import { getWritingVoice } from "./voiceLibrary.js";
import { getWorkspace } from "../workspaces/workspaceRegistry.js";
import { listWritingSources } from "./writingSources.js";

const MODE_SECTIONS: Record<WritingModeId, string[]> = {
  novel_studio: ["Scene setting", "Character beat", "Continuity check"],
  campaign_writing: ["Hook", "Community stake", "Call to action"],
  substack_blog: ["Lede", "Evidence block", "Closing reflection"],
  speech_debate: ["Opening line", "Three pillars", "Memorable close"],
  grant_strategy: ["Problem statement", "Approach", "Outcomes & metrics"],
  social_draft: ["Hook post", "Thread bullets", "Link CTA"],
};

export function previewDraft(input: {
  mode_id: WritingModeId;
  voice_id: WritingVoiceId;
  workspace_id: string;
  topic: string;
}): WritingDraftPreview | null {
  const mode = getWritingMode(input.mode_id);
  const voice = getWritingVoice(input.voice_id);
  const ws = getWorkspace(input.workspace_id);
  if (!mode || !voice || !ws) return null;

  const topic = input.topic.trim() || ws.current_focus || ws.title;
  const sections = MODE_SECTIONS[input.mode_id];
  const sources = listWritingSources(input.workspace_id).filter((s) => s.allowed).slice(0, 5);
  const sourcePaths = sources.map((s) => s.path);

  const markdown = `# ${mode.label} — Draft Preview (not saved)

**Workspace:** ${ws.title}  
**Voice:** ${voice.label}  
**Topic:** ${topic}  
**Guardrails:** Draft/preview only · No auto-publish · No file writes without approval

---

## Voice notes

${voice.tone_notes}

---

${sections
  .map(
    (section) => `## ${section}

_[${voice.label} draft for "${topic}" — ${section.toLowerCase()} placeholder. Connect approved sources in Sources tab before final generation.]_

`,
  )
  .join("")}

---

## Source-aware context

${
  sourcePaths.length
    ? sourcePaths.map((p) => `- \`${p}\``).join("\n")
    : "_No approved source files indexed for this workspace yet. Add filesystem roots or link Knowledge Explorer assets._"
}

---

## Next steps (approval-gated)

1. Review preview in Writing Department  
2. Pull additional sources from Knowledge Explorer  
3. When satisfied, propose save via Actions queue (LB-OS-010)  
4. **Never** auto-publish to Substack, social, or email from this preview

---

*Generated by Writing Department · read-only preview · LB-OS-013*
`;

  return {
    mode_id: input.mode_id,
    voice_id: input.voice_id,
    workspace_id: input.workspace_id,
    topic,
    markdown,
    source_paths: sourcePaths,
    read_only: true,
    publish_blocked: true,
  };
}
