import { fetchLiveJson } from "./fetchLive";

export type CompetitorEvidence = { name: string; category: string; pricing_note?: string; source_url?: string; evidence_status: "market_anchor" | "needs_refresh" | "internal_substitute" };
export type FoundryProduct = { id: string; name: string; kind: "software" | "platform" | "book" | "service" | "component"; readiness: number; disposition: string; annualLow: number; annualHigh: number; training: boolean; capstoneCandidate: boolean; sourceRepos: string[]; competitors: CompetitorEvidence[]; advantages: string[]; disadvantages: string[]; notes?: string };
export type MasterBuildPlan = { id: string; productId: string; title: string; status: "draft" | "accepted" | "active" | "complete" | "hold"; purpose: string; remainingReadinessPct: number; budgetUsd: number; capstoneEligible: boolean };
export type PhaseValueRecord = { phaseId: string; masterPlanId: string; productId: string; title: string; budgetUsd: number; phaseClass: string; status: "planned" | "active" | "submitted" | "accepted" | "rework" | "blocked"; acceptanceCriteria: string[]; evidenceRequired: string[]; acceptedEvidence: string[] };
export type FoundryProposalKind = "product_change" | "builder_application" | "phase_submission" | "capstone_application" | "master_plan_proposal" | "registry_change";
export type FoundryProposalStatus = "draft" | "submitted" | "under_review" | "accepted" | "rejected" | "withdrawn";
export type FoundryProposalRecord = { id: string; kind: FoundryProposalKind; subject_id: string | null; submitted_by: string; title: string; summary: string; payload_json: string; status: FoundryProposalStatus; created_at: string; updated_at: string };
export type FoundryEvidenceRecord = { id: string; proposal_id: string; evidence_type: string; label: string; uri: string | null; content_hash: string | null; notes: string | null; created_at: string };
export type FoundryAcceptanceRecord = { id: string; proposal_id: string; reviewer_id: string; decision: "accepted" | "rejected" | "rework"; rationale: string; created_at: string };
export type CompanyFoundrySnapshot = { meta: { schemaVersion: string; slice: string; mode: "read-first"; updated: string; cashForecastUntilPaidValidationUsd: number }; products: FoundryProduct[]; masterPlans: MasterBuildPlan[]; phases: PhaseValueRecord[]; builders: unknown[]; capstones: unknown[]; economicRules: { companyResidualFloorPct: number; capstoneLeadResidualCeilingPct: number; apprenticeHourlyRateUsd: number; defaultSettlementCadence: "monthly"; equityIssuanceEnabled: boolean; payrollEnabled: boolean; moneyMovementEnabled: boolean } };

export type AcademyEnrollment = { id: string; builder_id: string; cohort_id: string | null; status: "active" | "paused" | "remediation" | "graduation_ready" | "graduated" | "exited"; current_stage_id: string; current_module_id: string; started_at: string; completed_at: string | null; updated_at: string };
export type AcademyModuleProgress = { id: string; enrollment_id: string; module_id: string; status: "locked" | "available" | "in_progress" | "submitted" | "complete" | "remediation"; attempts: number; best_score: number | null; evidence_json: string; feedback_json: string; started_at: string | null; completed_at: string | null; updated_at: string };
export type AcademyGateRecord = { id: string; enrollment_id: string; stage_id: string; status: "not_ready" | "ready" | "passed" | "remediation"; evaluator_type: "system" | "human"; evaluator_id: string | null; rationale: string | null; passed_at: string | null; updated_at: string };
export type LearnerDashboard = { enrollment: AcademyEnrollment; currentStage: unknown; currentModule: unknown; progress: AcademyModuleProgress[]; gates: AcademyGateRecord[]; metrics: { modulesTotal: number; modulesComplete: number; percentComplete: number; remediationModules: number; stagesPassed: number; stagesTotal: number; capstoneRequiredForGraduation: boolean; graduationReady: boolean } };

export type ProductionAssignment = { id: string; phase_id: string; product_id: string; master_plan_id: string | null; builder_id: string; assigned_by: string; phase_band: number; pvs: number; contribution_share: number; budget_attribution_usd: number; compensation_note: string | null; status: "assigned" | "in_progress" | "submitted" | "rework" | "accepted" | "blocked"; packet_json: string; assigned_at: string; started_at: string | null; submitted_at: string | null; accepted_at: string | null; updated_at: string };
export type ProductionLabMetrics = { assignments: number; accepted: number; rework: number; plannedBudgetAttributionUsd: number; pvpAwarded: number; financialExecutionEnabled: boolean };

export type MasterPlanBuildRecord = { id: string; notebook_id: string; builder_id: string; title: string; status: "draft" | "assembling" | "red_team_ready" | "submitted" | "accepted" | "rework"; version: number; completeness_score: number; dependency_score: number; budget_total_usd: number; phase_count: number; red_team_score: number | null; created_at: string; updated_at: string };
export type MasterPlanDashboard = { build: MasterPlanBuildRecord; sections: unknown[]; phases: unknown[]; blockers: string[]; redTeamReady: boolean };

async function postFoundry<T>(path: string, body: unknown): Promise<T> {
  const response = await fetch(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const data = await response.json();
  if (!response.ok) throw new Error(data?.error ?? `Foundry request failed (${response.status})`);
  return data as T;
}

export async function fetchCompanyFoundrySnapshot(): Promise<CompanyFoundrySnapshot> { return fetchLiveJson<CompanyFoundrySnapshot>("/api/foundry/snapshot"); }
export async function fetchCompanyFoundryProduct(productId: string) { return fetchLiveJson<{ product: FoundryProduct; masterPlans: MasterBuildPlan[]; phases: PhaseValueRecord[] }>(`/api/foundry/products/${encodeURIComponent(productId)}`); }
export async function fetchCompanyFoundryValidation() { return fetchLiveJson<{ valid: boolean; errors: string[]; schemaVersion: string; slice: string }>("/api/foundry/validation"); }
export async function fetchFoundryProposals(): Promise<FoundryProposalRecord[]> { return (await fetchLiveJson<{ proposals: FoundryProposalRecord[] }>("/api/foundry/proposals")).proposals; }
export async function fetchFoundryProposalDetail(proposalId: string) { return fetchLiveJson<{ proposal: FoundryProposalRecord; evidence: FoundryEvidenceRecord[]; reviews: FoundryAcceptanceRecord[] }>(`/api/foundry/proposals/${encodeURIComponent(proposalId)}`); }
export async function createFoundryProposal(input: { kind: FoundryProposalKind; subjectId?: string; submittedBy: string; title: string; summary: string; payload?: unknown }): Promise<FoundryProposalRecord> { return (await postFoundry<{ proposal: FoundryProposalRecord }>("/api/foundry/proposals", input)).proposal; }
export async function submitFoundryProposal(proposalId: string, actorId: string): Promise<FoundryProposalRecord> { return (await postFoundry<{ proposal: FoundryProposalRecord }>(`/api/foundry/proposals/${encodeURIComponent(proposalId)}/submit`, { actorId })).proposal; }
export async function addFoundryProposalEvidence(proposalId: string, input: { actorId: string; evidenceType: string; label: string; uri?: string; contentHash?: string; notes?: string }): Promise<FoundryEvidenceRecord> { return (await postFoundry<{ evidence: FoundryEvidenceRecord }>(`/api/foundry/proposals/${encodeURIComponent(proposalId)}/evidence`, input)).evidence; }
export async function reviewFoundryProposal(proposalId: string, input: { reviewerId: string; decision: "accepted" | "rejected" | "rework"; rationale: string }): Promise<FoundryAcceptanceRecord> { return (await postFoundry<{ review: FoundryAcceptanceRecord }>(`/api/foundry/proposals/${encodeURIComponent(proposalId)}/review`, input)).review; }
export async function applyFoundryProposalEffect(proposalId: string, actorId: string): Promise<{ ok: boolean; effectType?: string; subjectId?: string }> { return postFoundry(`/api/foundry/proposals/${encodeURIComponent(proposalId)}/apply-effect`, { actorId }); }
export async function fetchFoundryBuilders(): Promise<unknown[]> { return (await fetchLiveJson<{ builders: unknown[] }>("/api/foundry/builders")).builders; }
export async function fetchFoundryCapabilityEvents(builderId?: string): Promise<unknown[]> { const q = builderId ? `?builderId=${encodeURIComponent(builderId)}` : ""; return (await fetchLiveJson<{ events: unknown[] }>(`/api/foundry/capability-events${q}`)).events; }
export async function fetchFoundryCohorts(): Promise<unknown[]> { return (await fetchLiveJson<{ cohorts: unknown[] }>("/api/foundry/cohorts")).cohorts; }
export async function fetchAdmittedFoundryMasterPlans(): Promise<unknown[]> { return (await fetchLiveJson<{ masterPlans: unknown[] }>("/api/foundry/admitted-master-plans")).masterPlans; }
export async function fetchFoundryAudit(limit = 100): Promise<unknown[]> { return (await fetchLiveJson<{ events: unknown[] }>(`/api/foundry/audit?limit=${limit}`)).events; }
export async function fetchFoundryWriteCapabilities(): Promise<Record<string, boolean>> { return fetchLiveJson<Record<string, boolean>>("/api/foundry/write-capabilities"); }

export async function fetchAcademyEnrollments(): Promise<AcademyEnrollment[]> { return (await fetchLiveJson<{ enrollments: AcademyEnrollment[] }>("/api/foundry/academy/enrollments")).enrollments; }
export async function enrollAcademyBuilder(builderId: string, cohortId?: string): Promise<AcademyEnrollment> { return (await postFoundry<{ enrollment: AcademyEnrollment }>("/api/foundry/academy/enrollments", { builderId, cohortId })).enrollment; }
export async function fetchLearnerDashboard(enrollmentId: string): Promise<LearnerDashboard> { return fetchLiveJson<LearnerDashboard>(`/api/foundry/academy/enrollments/${encodeURIComponent(enrollmentId)}/dashboard`); }
export async function startAcademyModule(enrollmentId: string, moduleId: string): Promise<AcademyModuleProgress> { return (await postFoundry<{ progress: AcademyModuleProgress }>(`/api/foundry/academy/enrollments/${encodeURIComponent(enrollmentId)}/modules/${encodeURIComponent(moduleId)}/start`, {})).progress; }
export async function submitAcademyModuleAttempt(enrollmentId: string, moduleId: string, input: { passed: boolean; score?: number; evidence?: unknown[]; feedback?: unknown[] }): Promise<LearnerDashboard> { return (await postFoundry<{ progress: AcademyModuleProgress; dashboard: LearnerDashboard }>(`/api/foundry/academy/enrollments/${encodeURIComponent(enrollmentId)}/modules/${encodeURIComponent(moduleId)}/attempt`, input)).dashboard; }
export async function decideAcademyStageGate(enrollmentId: string, stageId: string, input: { evaluatorId: string; passed: boolean; rationale: string }): Promise<LearnerDashboard> { return (await postFoundry<{ gate: AcademyGateRecord; dashboard: LearnerDashboard }>(`/api/foundry/academy/enrollments/${encodeURIComponent(enrollmentId)}/stages/${encodeURIComponent(stageId)}/gate`, input)).dashboard; }

export async function fetchProductionLabMetrics(): Promise<ProductionLabMetrics> { return fetchLiveJson<ProductionLabMetrics>("/api/foundry/production-lab/metrics"); }
export async function fetchProductionAssignments(builderId?: string): Promise<ProductionAssignment[]> { const q = builderId ? `?builderId=${encodeURIComponent(builderId)}` : ""; return (await fetchLiveJson<{ assignments: ProductionAssignment[] }>(`/api/foundry/production-lab/assignments${q}`)).assignments; }
export async function fetchProductionAssignmentDetail(assignmentId: string): Promise<unknown> { return fetchLiveJson(`/api/foundry/production-lab/assignments/${encodeURIComponent(assignmentId)}`); }
export async function fetchEligibleProductionPhases(builderId: string): Promise<PhaseValueRecord[]> { return (await fetchLiveJson<{ phases: PhaseValueRecord[] }>(`/api/foundry/production-lab/eligible/${encodeURIComponent(builderId)}`)).phases; }
export async function assignProductionPhase(input: { phaseId: string; builderId: string; assignedBy: string; pvs: number; contributionShare?: number; budgetAttributionUsd?: number; compensationNote?: string }): Promise<ProductionAssignment> { return (await postFoundry<{ ok: boolean; assignment: ProductionAssignment }>("/api/foundry/production-lab/assignments", input)).assignment; }
export async function startProductionAssignment(assignmentId: string, builderId: string): Promise<ProductionAssignment> { return (await postFoundry<{ ok: boolean; assignment: ProductionAssignment }>(`/api/foundry/production-lab/assignments/${encodeURIComponent(assignmentId)}/start`, { builderId })).assignment; }
export async function submitProductionAssignment(assignmentId: string, input: { builderId: string; summary: string; evidence: unknown[]; validation: unknown[]; knownLimits?: unknown[] }): Promise<unknown> { return postFoundry(`/api/foundry/production-lab/assignments/${encodeURIComponent(assignmentId)}/submit`, input); }
export async function reviewProductionAssignment(assignmentId: string, input: { submissionId: string; reviewerId: string; decision: "accepted" | "rework" | "rejected"; rationale: string; qualityMultiplier?: number }): Promise<{ pvpAwarded: number }> { return postFoundry(`/api/foundry/production-lab/assignments/${encodeURIComponent(assignmentId)}/review`, input); }

export async function ensureMasterPlanBuilder(notebookId: string): Promise<MasterPlanDashboard> { return (await postFoundry<{ build: MasterPlanBuildRecord; dashboard: MasterPlanDashboard }>(`/api/foundry/master-plan-builder/notebooks/${encodeURIComponent(notebookId)}/ensure`, {})).dashboard; }
export async function fetchMasterPlanByNotebook(notebookId: string): Promise<MasterPlanDashboard> { return fetchLiveJson<MasterPlanDashboard>(`/api/foundry/master-plan-builder/notebooks/${encodeURIComponent(notebookId)}`); }
export async function fetchMasterPlanBuilder(buildId: string): Promise<MasterPlanDashboard> { return fetchLiveJson<MasterPlanDashboard>(`/api/foundry/master-plan-builder/${encodeURIComponent(buildId)}`); }
export async function assembleMasterPlanBuilder(buildId: string): Promise<MasterPlanDashboard> { return (await postFoundry<{ build: MasterPlanBuildRecord; dashboard: MasterPlanDashboard }>(`/api/foundry/master-plan-builder/${encodeURIComponent(buildId)}/assemble`, {})).dashboard; }
export async function upsertMasterPlanBuilderPhase(buildId: string, input: { phaseKey: string; title: string; sequenceNo: number; dependencies?: string[]; acceptance?: string[]; pvs?: number; budgetUsd?: number; staffing?: unknown[] }): Promise<MasterPlanDashboard> { return (await postFoundry<{ phases: unknown[]; dashboard: MasterPlanDashboard }>(`/api/foundry/master-plan-builder/${encodeURIComponent(buildId)}/phases`, input)).dashboard; }
export async function redTeamMasterPlanBuilder(buildId: string, input: { reviewerId: string; score: number; findings?: unknown[]; decision: "pass" | "conditional" | "rework"; rationale: string }): Promise<MasterPlanDashboard> { return (await postFoundry<{ result: unknown; dashboard: MasterPlanDashboard }>(`/api/foundry/master-plan-builder/${encodeURIComponent(buildId)}/red-team`, input)).dashboard; }
export async function exportMasterPlanBuilder(buildId: string): Promise<unknown> { return fetchLiveJson(`/api/foundry/master-plan-builder/${encodeURIComponent(buildId)}/export`); }
