import cors from "cors";
import express from "express";
import { bootstrapApp } from "./bootstrap.js";
import { isDatabaseConnected } from "./db/database.js";
import { commandRouter } from "./command.js";
import { healthRouter } from "./health.js";
import { safetyRouter } from "./routes/safety.js";
import { workspacesRouter } from "./routes/workspaces.js";
import { modulesRouter } from "./routes/modules.js";
import { assetsRouter } from "./routes/assets.js";
import { actionsRouter } from "./routes/actions.js";
import { filesRouter } from "./routes/files.js";
import { knowledgeExplorerRouter } from "./routes/knowledgeExplorer.js";
import { cosRouter } from "./routes/cos.js";
import { systemRouter } from "./routes/system.js";
import { epoRouter } from "./routes/epo.js";
import { engineeringRouter } from "./routes/engineering.js";
import { writingRouter } from "./routes/writing.js";
import { dataIntelligenceRouter } from "./routes/dataIntelligence.js";
import { relationshipNetworkRouter } from "./routes/relationshipNetwork.js";
import { contactsRouter } from "./routes/contacts.js";
import { ucieRouter } from "./routes/ucie.js";
import { vopRouter } from "./routes/vop.js";
import { communicationsDraftsRouter } from "./routes/communicationsDrafts.js";
import { v1Router } from "./routes/v1.js";
import { providersRouter } from "./routes/providers.js";
import { migrationRouter } from "./routes/migration.js";
import { consolidationRouter } from "./routes/consolidation.js";
import { integrationRouter } from "./routes/integration.js";
import { liveSurfaceRouter } from "./routes/liveSurface.js";
import { companyFoundryRouter } from "./routes/companyFoundry.js";
import { settingsRouter } from "./settings/settingsRoutes.js";
import { factoryRouter } from "./factory/factoryRoutes.js";
import { getRegisteredModules } from "./core/moduleLoader.js";
import { runBackgroundIndex } from "./knowledgeExplorer/indexer.js";

const port = Number(process.env.LOCALBRAIN_PORT ?? 4545);

bootstrapApp();
runBackgroundIndex();

const app = express();

app.use(cors());
app.use(express.json());
app.use("/api", healthRouter);
app.use("/api", commandRouter);
app.use("/api", safetyRouter);
app.use("/api", workspacesRouter);
app.use("/api", modulesRouter);
app.use("/api", assetsRouter);
app.use("/api", actionsRouter);
app.use("/api", filesRouter);
app.use("/api", knowledgeExplorerRouter);
app.use("/api", cosRouter);
app.use("/api", systemRouter);
app.use("/api", epoRouter);
app.use("/api", engineeringRouter);
app.use("/api", writingRouter);
app.use("/api", dataIntelligenceRouter);
app.use("/api", relationshipNetworkRouter);
app.use("/api", contactsRouter);
app.use("/api", ucieRouter);
app.use("/api", vopRouter);
app.use("/api", communicationsDraftsRouter);
app.use("/api", v1Router);
app.use("/api", providersRouter);
app.use("/api", migrationRouter);
app.use("/api", consolidationRouter);
app.use("/api", integrationRouter);
app.use("/api", liveSurfaceRouter);
app.use("/api", companyFoundryRouter);
app.use("/api", settingsRouter);
app.use("/api", factoryRouter);

app.listen(port, () => {
  const db = isDatabaseConnected();
  const modules = getRegisteredModules();
  console.log(`LocalBrain backend listening on http://localhost:${port}`);
  console.log(`Permission engine v2 — database ${db ? "connected" : "FAILED"}`);
  console.log(`Module loader — ${modules.length} manifests registered (LB-OS-106)`);
});
