import { Router } from "express";
import { decideCapstone, ensureCapstoneApplication, getCapstoneDefenseDashboard, recordCapstoneDefense, redTeamCapstone, submitCapstoneApplication } from "../companyFoundry/capstoneDefense.js";
export const capstoneDefenseRouter=Router();
capstoneDefenseRouter.post("/foundry/capstone-applications",(req,res)=>{const a=ensureCapstoneApplication(String(req.body?.notebookId??""),String(req.body?.buildId??""));return a?res.status(201).json({application:a}):res.status(409).json({error:"application_not_creatable"});});
capstoneDefenseRouter.post("/foundry/capstone-applications/:id/submit",(req,res)=>{const r=submitCapstoneApplication({applicationId:req.params.id,builderId:String(req.body?.builderId??""),application:req.body?.application??{}});return r.ok?res.json(r):res.status(409).json(r);});
capstoneDefenseRouter.post("/foundry/capstone-applications/:id/red-team",(req,res)=>{const r=redTeamCapstone({applicationId:req.params.id,reviewerId:String(req.body?.reviewerId??""),marketScore:Number(req.body?.marketScore),technicalScore:Number(req.body?.technicalScore),economicScore:Number(req.body?.economicScore),executionScore:Number(req.body?.executionScore),findings:req.body?.findings,recommendation:req.body?.recommendation,rationale:String(req.body?.rationale??"")});return r.ok?res.status(201).json(r):res.status(r.error==="self_review_forbidden"?403:409).json(r);});
capstoneDefenseRouter.post("/foundry/capstone-applications/:id/defense",(req,res)=>{const r=recordCapstoneDefense({applicationId:req.params.id,defenderId:String(req.body?.defenderId??""),panel:Array.isArray(req.body?.panel)?req.body.panel:[],answers:req.body?.answers,score:Number(req.body?.score),rationale:String(req.body?.rationale??"")});return r.ok?res.status(201).json(r):res.status(409).json(r);});
capstoneDefenseRouter.post("/foundry/capstone-applications/:id/decision",(req,res)=>{const r=decideCapstone({applicationId:req.params.id,decidedBy:String(req.body?.decidedBy??""),graduationDecision:req.body?.graduationDecision,pilotDecision:req.body?.pilotDecision,rationale:String(req.body?.rationale??"")});return r.ok?res.status(201).json(r):res.status(r.error==="self_decision_forbidden"?403:409).json(r);});
capstoneDefenseRouter.get("/foundry/capstone-applications/:id",(req,res)=>{const d=getCapstoneDefenseDashboard(req.params.id);return d?res.json(d):res.status(404).json({error:"application_not_found"});});
