import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import type { BurtPacketPreview, BurtPacketSummary } from "@localbrain/shared";
import { getRepoRoot } from "../db/repoRoot.js";
import { parsePhaseChecklistSlices } from "../epo/checklistParser.js";
import { readdirSync } from "node:fs";

export function listBurtPacketHistory(): BurtPacketSummary[] {
  const slices = parsePhaseChecklistSlices();
  const root = getRepoRoot();
  const dir = join(root, "docs", "burt_packets");
  const onDisk = existsSync(dir)
    ? readdirSync(dir)
        .filter((f) => f.endsWith(".md"))
        .map((f) => f.replace(".md", ""))
    : [];

  const summaries: BurtPacketSummary[] = [];
  for (const s of slices) {
    if (!s.burt_packet_path) continue;
    summaries.push({
      slice_id: s.slice_id,
      path: s.burt_packet_path,
      title: s.name,
      status: s.status,
    });
  }

  for (const name of onDisk) {
    if (!summaries.some((s) => s.path?.includes(name))) {
      summaries.push({
        slice_id: name.match(/LB-OS-[\d.]+/)?.[0] ?? null,
        path: `docs/burt_packets/${name}.md`,
        title: name,
        status: "on_disk",
      });
    }
  }

  return summaries.sort((a, b) => (b.slice_id ?? "").localeCompare(a.slice_id ?? ""));
}

export function previewBurtPacket(input: {
  slice_id?: string;
  title?: string;
}): BurtPacketPreview {
  const root = getRepoRoot();
  const sliceId = input.slice_id?.trim() || "LB-OS-XXX";
  const title = input.title?.trim() || "New slice";
  const exportPath = `docs/burt_packets/${sliceId}.md`;

  const existing = join(root, exportPath);
  if (existsSync(existing)) {
    return {
      slice_id: sliceId,
      title,
      markdown: readFileSync(existing, "utf8"),
      export_path: exportPath,
      read_only: true,
    };
  }

  const markdown = `# BURT / CURSOR EXECUTION SCRIPT

**Project:** LocalBrain  
**Slice:** ${sliceId}  
**Status:** 📋 DRAFT — preview only (no write)  
**Authoritative spec:** (link spec doc)

---

## Mission

${title}

---

## Hard boundaries

\`\`\`txt
Read-only where not explicitly approved
No shell · no git writes · no auto-execution
All file changes via LB-OS-010 approval queue
\`\`\`

---

## Build checklist

\`\`\`txt
[ ] Scope defined
[ ] GET /api routes (if applicable)
[ ] UI shell
[ ] Tests
[ ] npm run check && npm run test pass
\`\`\`

---

## Commit (when complete)

\`feat: …\`

---

*${sliceId} · preview generated by Engineering Department · read-only*
`;

  return {
    slice_id: sliceId,
    title,
    markdown,
    export_path: exportPath,
    read_only: true,
  };
}
